name: CI Checks
on: [push, pull_request]  # Запуск при пуше и в PR

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20  # или ваша версия Node.js

      - name: Install dependencies
        run: npm install
      - name: SonarQube Scan
        env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
          -Dsonar.coverage.exclusions=**/* \
          -Dsonar.cpd.exclusions=**/* \
          -Dsonar.forceAnalysis=true

      - name: Run linter (ESLint)
        run: npx eslint .  # Проверка стиля кода

      - name: Build project
        run: npm run build